import type { Post } from '@/types';

export const SEED_POSTS: Omit<Post, 'user_id'>[] = [
  {
    id: 'seed-1',
    created_at: '2026-04-01T10:00:00Z',
    title: 'Crook Kitchen Transformation',
    date: '2026-04-03',
    pillar: 'before_after',
    status: 'published',
    platforms: ['instagram', 'facebook', 'pinterest'],
    format: 'carousel',
    caption: 'The Maryville kitchen that went from dated to stunning 🤯\n\nBEFORE: Dark oak cabinets from 1998, laminate counters, fluorescent lighting.\nAFTER: Custom shaker cabinets in Sherwin Williams Alabaster, quartzite counters, and under-cabinet LED strips.\n\nThis Maryville homeowner trusted us to bring their vision to life — and we delivered.\n\nThinking about transforming your kitchen? Let\'s talk. Free design consultation — link in bio or call 865.681.4039.\n\n#KeystoneKitchens #KitchenTransformation #BeforeAndAfter #MaryvilleKitchen #CustomCabinets #TennesseeHomes',
    notes: 'Used carousel format. Before on slide 1, after on slides 2-4. Pinned to top of profile.',
  },
  {
    id: 'seed-2',
    created_at: '2026-04-05T10:00:00Z',
    title: 'Cabinet Depth Design Tip',
    date: '2026-04-08',
    pillar: 'design_tips',
    status: 'scheduled',
    platforms: ['instagram', 'facebook', 'tiktok'],
    format: 'carousel',
    caption: 'Kitchen design tip from our shop floor 👇\n\nMost homeowners don\'t realize that standard 24" deep base cabinets eat almost 2 feet of your kitchen. Here\'s what we recommend:\n\n✅ Consider 21" deep bases for galley kitchens\n✅ Soft-close everything. Your future self will thank you\n✅ Invest in the boxes, not just the doors\n\nWe\'ve built 200+ custom kitchens across Tennessee. These are the details that separate good from great.\n\nSave this for your renovation planning 📌\n\n#KeystoneKitchens #KitchenDesignTips #CustomCabinets',
    notes: 'Schedule for Tuesday 9am. Carousel format with each tip as a separate slide.',
  },
  {
    id: 'seed-3',
    created_at: '2026-04-10T10:00:00Z',
    title: 'Walnut Island Build — Shop Video',
    date: '2026-04-15',
    pillar: 'process',
    status: 'approved',
    platforms: ['instagram', 'tiktok'],
    format: 'reel',
    caption: 'Ever wonder what goes into building a custom kitchen? Here\'s a look inside our Maryville shop 🔨\n\nThis waterfall walnut island is being built for a family in Knoxville. Every piece is:\n\n→ Cut and assembled by hand in our Tennessee shop\n→ Finished with hand-rubbed oil\n→ Built to last decades, not just years\n\nFrom raw American walnut to installed in your home — that\'s the Keystone difference.\n\n#KeystoneKitchens #CustomCabinetry #Handcrafted #MadeInTennessee #Woodworking',
    notes: 'Film the sanding and oil application. Raw audio, no music. 30-45 second reel.',
  },
  {
    id: 'seed-4',
    created_at: '2026-04-12T10:00:00Z',
    title: 'Harrison Family Testimonial',
    date: '2026-04-22',
    pillar: 'client_story',
    status: 'drafted',
    platforms: ['instagram', 'facebook', 'google_business'],
    format: 'post',
    caption: '"We never thought our kitchen could look like this. Keystone made it happen." — Madison H., Knoxville\n\nWhen the Harrison family came to us, they wanted a modern farmhouse kitchen that felt warm but not trendy. We designed custom white oak shaker cabinets with brass hardware and a 10-foot island.\n\n8 weeks from first meeting to final installation.\n\nYour kitchen story starts with a conversation. Free consultation — link in bio.\n\n#KeystoneKitchens #HappyClients #ClientStory #KnoxvilleKitchen',
    notes: 'Get video testimonial from Madison. She agreed to be filmed. Schedule shoot for April 18.',
  },
  {
    id: 'seed-5',
    created_at: '2026-04-14T10:00:00Z',
    title: 'Spring Consultation Push',
    date: '2026-04-25',
    pillar: 'offer',
    status: 'idea',
    platforms: ['instagram', 'facebook', 'google_business'],
    format: 'story',
    caption: 'Planning a kitchen renovation this summer? Let\'s talk before you pick a single cabinet door.\n\nHere\'s what you get in a free Keystone design consultation:\n\n🏠 In-home measurement and assessment\n🎨 Style direction based on YOUR home\n📐 3D design preview of your new kitchen\n💰 Transparent pricing — no surprises\n\nWe book 8 consultations per month and May is filling up.\n\n→ DM us "KITCHEN" or call 865.681.4039\n\n#KeystoneKitchens #FreeConsultation #KitchenRenovation',
    notes: 'Boost with $30 on FB/IG. Target homeowners 30-55, Knoxville/Maryville metro, household income $100k+.',
  },
  {
    id: 'seed-6',
    created_at: '2026-04-16T10:00:00Z',
    title: 'Warm Minimalism Kitchen Trend',
    date: '2026-04-29',
    pillar: 'trend',
    status: 'idea',
    platforms: ['instagram', 'pinterest', 'tiktok'],
    format: 'reel',
    caption: 'Warm minimalism is taking over Tennessee kitchens in 2026 — and we\'re here for it 🔮\n\nWhat it looks like:\n→ Rift-cut white oak cabinets with minimal hardware\n→ Integrated appliance panels for a seamless look\n→ Natural stone in warm tones — think honey onyx, not cold marble\n\nWe just built a warm minimalist kitchen in Knoxville and the result is stunning.\n\nThinking about bringing this style home? Free consultation — link in bio.\n\n#KeystoneKitchens #KitchenTrends #WarmMinimalism #CustomCabinets',
    notes: 'Source inspiration images from recent Knoxville project. Pin to "2026 Kitchen Trends" Pinterest board.',
  },
];
